### PR TITLE
Performance edits

### PR DESCRIPTION
**Pull request by dregimbal**

### CODE REVIEW

**Comment by dregimbal** [comment]
Whoops, I didn't realize that pushing to the branch after I had opened the PR would add the commits to it. 
You'll probably want to only pull in up to the "add in some semicolons" commit, since that's the commit where I've tried to modify my code to fit more towards your code style, before I ran eslint against the code. 
My master branch has a couple other changes like updating the version number, some building instructions for others trying to work with the code, and a small CSS fix

**Comment by KernelZechs** [comment]
@dregimbal okay so I'm going to be honest, I'm a bit overwhelmed looking at this and it will require a lot of regression. I was only expecting to see the performance tuning in this PR. Some key takeaways from this would be:

- Remove the ESLint and reformatting, OJD3 has eslint rules as well as a webpack builder so for me to use this (and to the spec I like, I'm extremely picky on eslint rules) would require me to redo this. (Examples can be found https://github.com/KernelZechs/open-randomizer-tracker and https://github.com/KernelZechs/mono-switcher). 

- There is too much to digest here to encompass upon a single PR with the goal and it's out of scope. Please make a separate PR with your performance changes.

To give you some history on why this is so convoluted is that it started as a small project for *me* and quickly grew out of hand by feature requests in such a short time frame (this project is only a year old). This is why it is being rewritten, I would rather just delta small beneficial changes at this point so I can focus on the rewrite which will have better code quality overall. 

I do appreciate you taking the time to do it though, it means a lot. Let's pull this back a bit so we can get the beneficial changes out. I'm hoping to finish OJD3 in the next month or two, not that I have anything better to do- I'm stuck in my house.

Thanks.

**Comment by dregimbal** [comment]
I fully understand being picky on rules, it's nice when things fit the same standard.
Would you be able to update this repo with an ESLint config file? My machine config files conflict quite a bit with yours, and I'm having trouble trying to use the one from the mono-switcher repo.

Is the new code-base/rewrite public anywhere, or are you going to release it when it's completed?

I'll try to break my changes into smaller PRs 😄

**Comment by KernelZechs** [comment]
@dregimbal thanks for understanding. And no- the rules set forth in my other repos are based upon google's react standard with some modifications that I like. Truth be told no eslint ruleset is the same between projects if you look at some of the major ones in the NodeJS land, I would just suggest turning off your eslint for this project. I'm not going to judge since my own code isn't even `clean` by my standards.

The rewrite isn't public yet, I'm trying to finish it up before I throw it in here. Last thing I like to do is have non-working code I have to answer support requests to.

Let me know when you have a new PR, I've also added a build guide for 2.x at the request of another issuer as they are trying to get it into Arch AUR repo: 

https://github.com/KernelZechs/open-joystick-display/blob/master/BUILD.md

**Pull request closed without merging**
