### PR TITLE
Enhancement - PS4 Controller Themes

### PR DESCRIPTION
**Pull request by jph168**
Ps4 Ds4 Addition For Gamers/Streamers to use in Open joystick Display.

### CODE REVIEW

**Comment by KernelZechs** [comment]
@jph168 this is great! Thank you for doing this, I'm currently out on vacation but when I get back this week I'll review this PR, but from the assets it looks pretty solid.

**Comment by jph168** [comment]
No problem. I can fix these, additionally the options and share buttons do not seem to be actually tied to anything from them not working for the scuf ps4 controller either.

**Comment by jph168** [comment]
So I deleted my fork of the project by mistake.., Is there any possible way to update this pull request without making another? Otherwise I have the files here.
[ojd-sony-ps4.zip](https://github.com/KernelZechs/open-joystick-display/files/4330576/ojd-sony-ps4.zip)

**Comment by KernelZechs** [comment]
@jph168 unfortunately I can't. So I'll close this and just do up a new pull request. Don't stress over it.

**Comment by jph168** [comment]
> @jph168 unfortunately I can't. So I'll close this and just do up a new pull request. Don't stress over it.

Thanks sorry about that again, Glad I could contribute back, least I could do for an awesome project :)

**Pull request closed without merging**
